Push code if audit fails
Signed-off-by: Bhavin Gandhi <bhavin7392@gmail.com>

diff --git a/.github/workflows/new-version.yaml b/.github/workflows/new-version.yaml
--- a/.github/workflows/new-version.yaml
+++ b/.github/workflows/new-version.yaml
@@ -1,19 +1,20 @@
-name: "Update version"
+name: "Update formula version"
 on:
-  push:
-    branches:
-    - master
-    - version-update
   repository_dispatch:
     types:
     - update-on-release
-  pull_request:
 jobs:
   update-version:
-    if: github.event_name == 'repository_dispatch'
+    if: >
+      github.event_name == 'repository_dispatch'
+      && github.event.client_payload.prerelease == 'false'
     runs-on: macos-latest
     steps:
     - uses: actions/checkout@v2
+    - name: "Configure git"
+      run: |
+        git config user.name 'YugaByte CI'
+        git config user.email 'yugabyte-ci@users.noreply.github.com'
     - name: "Extract version number from tag"
       id: extract-version
       run: |
@@ -37,6 +38,7 @@ jobs:
         .ci/update_formula_version.sh '${{steps.extract-version.outputs.yb_version}}'
     - name: "Run brew audit on changed Formula files"
       id: run-audit
+      continue-on-error: true
       run: |
         for file in ${{steps.update-yb-formula.outputs.modified_files}}; do
           if [[ "${file}" =~ .*\/Formula\/yugabytedb(@[0-9]+\.[0-9]+)?\.rb ]]; then
@@ -44,19 +46,23 @@ jobs:
           fi
         done
     - name: "Push the changes"
+      if: steps.run-audit.outcome == 'success'
       run: |
-        git config user.name 'YugaByte CI'
-        git config user.email 'yugabyte-ci@users.noreply.github.com'
+        git status
+        git diff
         git add ${{steps.update-yb-formula.outputs.modified_files}}
         git commit -m "Update the version to ${{steps.extract-version.outputs.yb_version}}"
         # TODO: update this before merging
         git push -f origin ${{ github.ref }}:bot-branch
     - name: "Push the changes to a branch"
-      if: steps.run-audit.conclusion == 'failure'
+      if: steps.run-audit.outcome == 'failure'
       run: |
-        git config user.name 'YugaByte CI'
-        git config user.email 'yugabyte-ci@users.noreply.github.com'
+        git status
+        git diff
         git add ${{steps.update-yb-formula.outputs.modified_files}}
         git commit -m "Update the version to ${{steps.extract-version.outputs.yb_version}}"
-        # TODO: update this before merging: remove bot-branch
-        git push -f origin ${{ github.ref }}:bot-branch-update-${{steps.extract-version.outputs.yb_version}}
+        branch_name="update-${{steps.extract-version.outputs.yb_version}}-${{github.run_id}}"
+        git push origin ${{ github.ref }}:${branch_name}
+        echo "The 'run-audit' step for modified files has failed, please check the logs of 'audit-run' step for more details" 1>&2
+        echo "The modified files are pushed to https://github.com/${{github.repository}}/tree/${branch_name}" 1>&2
+        exit 1
